package ds

var (
	T2_COLOR_BODY           DsColor = COLOR_GRAY_950
	T2_COLOR_CONTENT        DsColor = COLOR_GRAY_50
	T2_COLOR_CONTENT_ACCENT DsColor = COLOR_GRAY_200
	T2_COLOR_SURFACE_LIGHT  DsColor = COLOR_GRAY_400
	T2_COLOR_SURFACE        DsColor = COLOR_GRAY_500
	T2_COLOR_SURFACE_DARK   DsColor = COLOR_GRAY_600
	T2_COLOR_HIGHLIGHT      DsColor = COLOR_BLUE_400
	T2_COLOR_PRIMARY        DsColor = COLOR_BRAND
	T2_COLOR_PRIMARY_HOT    DsColor = COLOR_BRAND_DARK
	T2_COLOR_PRIMARY_ACTIVE DsColor = COLOR_BRAND_LIGHT
	T2_COLOR_ON_PRIMARY     DsColor = COLOR_GRAY_50

	T2_BORDER DsColor = COLOR_GRAY_400

	T2_PANEL_GAP    DsSpacing = SPACING_2
	T2_BODY_PADDING DsSpacing = SPACING_2
)
