package designSystem

var (
	DS_T2_COLOR_CONTENT        DsColor = DS_COLOR_GRAY_50
	DS_T2_COLOR_CONTENT_ACCENT DsColor = DS_COLOR_GRAY_200
	DS_T2_COLOR_SURFACE_LIGHT  DsColor = DS_COLOR_GRAY_400
	DS_T2_COLOR_SURFACE        DsColor = DS_COLOR_GRAY_500
	DS_T2_COLOR_SURFACE_DARK   DsColor = DS_COLOR_GRAY_600
	DS_T2_COLOR_HIGHLIGHT      DsColor = DS_COLOR_BLUE_400
	DS_T2_COLOR_PRIMARY        DsColor = DS_COLOR_BRAND
	DS_T2_COLOR_ON_PRIMARY     DsColor = DS_COLOR_GRAY_50

	DS_T2_BORDER DsColor = DS_COLOR_GRAY_400
)
